import sharp from "sharp";
import { readdirSync, writeFileSync } from "fs";
import path from "path";

const dir = path.resolve("public/images");
const files = readdirSync(dir).filter((f) => f.endsWith(".jpg"));

const result = {};
for (const file of files) {
  const buf = await sharp(path.join(dir, file))
    .resize(16)
    .jpeg({ quality: 40 })
    .toBuffer();
  const key = "/images/" + file;
  result[key] = "data:image/jpeg;base64," + buf.toString("base64");
  console.log("done", file);
}

const out =
  "// Auto-generated by scripts/gen-blur.mjs — do not edit by hand.\n" +
  "export const BLUR_DATA: Record<string, string> = " +
  JSON.stringify(result, null, 2) +
  ";\n";

writeFileSync(path.resolve("src/lib/blur-data.ts"), out);
console.log("written src/lib/blur-data.ts");
